### ISSUE TITLE
What does Overwrite/Force settings do?

### ISSUE THREAD

**Issue by Vaarelsauce** [EnanoFurtivo/Osu-Mp3-Extractor#2]
I was wondering what exactly does the "Overwrite Album/Artist/Title", as well as the "Force Album/Artist/Title" checkboxes do in the Extractor GUI, since there wasn't any explanation about overwriting in the README file.

**Comment by EnanoFurtivo** [comment]
Hey, thanks for letting me know. It seems that when I created the project I wrote a more comprehensive description in the osu! forums [here](https://osu.ppy.sh/community/forums/topics/759672).

### Here is what you're looking for

![image](https://user-images.githubusercontent.com/31115763/178617225-0a92392c-879c-4749-8483-b3ae09dc2595.png)

**Pd. Might update the README file if I have some spare time I guess.**
